### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by xmha97** [anufrievroman/calcure#1]
How I can install this on Windows?

**Comment by anufrievroman** [comment]
Hello, for example, you can install as follows:

1. Install `Windows Terminal` app from the store
2. Install `python 3.x` also from the store (if you just type `python` in the Terminal app it will offer you to install).
3. Install a few libraries by typing in the Terminal `pip install holidays windows-curses`
4. Download this repository and extract the `calcure` file somewhere, for this example I'll use `Documents` folder.
5. Now you can finally run it by typing in the terminal `python ./Documents/calcure`

This is a bit bothersome, and I guess there should be a nicer way to do it. I'll update if I find something...

**Comment by xmha97** [comment]
Ok, thanks.

**Comment by xmha97** [comment]
Not working :(
![image](https://user-images.githubusercontent.com/23485114/148876644-f6c0b55d-7933-437b-b48e-5cfc4f550581.png)

**Comment by anufrievroman** [comment]
I assume you didn't change the config.ini. I think it might be related to encoding. I'll be able to take a look later today...

**Comment by xmha97** [comment]
I can't see config.ini
![image](https://user-images.githubusercontent.com/23485114/148879909-e7f8da2e-be70-47a2-af81-2bbabd05edc5.png)

**Comment by anufrievroman** [comment]
So yes, it was encoding problem. Try again with the version I just uploaded, please.

By the way, on Windows config is stored in your $HOME directory `\.config\calcure\config.ini` in my case it was `c:\Users\myname\.config\calcure\config.ini` or something like that.

**Comment by xmha97** [comment]
Now I don't have issue.
