### ISSUE TITLE
ics_event_files error

### ISSUE THREAD

**Issue by kyu0114** [anufrievroman/calcure#102]
Hi,

I am trying to use google calendar ics and I used the default config file and put the following line at the bottom of the config.ini

`ics_event_files = https://calendar.google.com/calendar/ical/xxxxxxx%40gmail.com/private-xxxxxxx/basic.ics`

I have changed my email and private key to xxxx (but used the actual one in the config file).
When I tried to run, it displayed the following error:

`ERROR:root:Looks like there is a problem in your config.ini file. Perhaps you edited it and entered a wrong line. Try removing your config.ini file and run the program again, it will create a fresh working config file.`

I am using Gentoo and I installed Calcure on venv using the pipx install calcure command. The calcure version is 3.0.2.

If I change the ics address to the folder address, no error comes up. Is this because I am using inside venv or is Gentoo not supported?

**Comment by anufrievroman** [comment]
You can't put it in the bottom of config, you need to replace the line in the corresponding section of the config. I think this might be the problem.

**Comment by kyu0114** [comment]
> You can't put it in the bottom of config, you need to replace the line in the corresponding section of the config. I think this might be the problem.
> 
> If that doesn't help, could you check what the log file in the config directory says?
> 
> This error basically says that errors occurred during parsing config, which typically means that some lines are in the wrong section or something like that.

NICE!!!

I removed calcurse_event_file line and replaced with ics_event_files as above and it worked!!!!!!!!!!!!!!

**Comment by anufrievroman** [comment]
Glad that helped :)
