### ISSUE TITLE
Transparency in windows

### ISSUE THREAD

**Issue by AB10110F** [anufrievroman/calcure#103]
I presume transparency is not supported on windows, or am I overlooking something perhaps?

**Comment by anufrievroman** [comment]
Now sure, but basically the default background color is set to "-1", i.e. no color. Then it's up to your terminal to respect this setting (usually they do). But then it's also up to your terminal to support transparency of it's window. Usually transparency is the global setting of the terminal or window manager, not specific to the application. I think Alacritty terminal should work.

**Comment by AB10110F** [comment]
Sorry I forgot to mention the terminal, it is windows terminal, and yeah it is probably a problem with that, thank you.

**Comment by AB10110F** [comment]
I'll be using it with other terminal
