### ISSUE TITLE
Update documentation to indicate how to setup holidays for a country with subdivisions

### ISSUE THREAD

**Issue by wolterhv** [anufrievroman/calcure#106]
Regarding the recent merge of #105, the documentation should be updated to indicate how to setup holidays for a country with subdivisions. It seems to me that the documentation is in another repository, so I haven't submitted a PR for this.

**Comment by anufrievroman** [comment]
Sure, I usually update docs when I officially publish the feature in a new release. So, I'll update it sometime soon.

**Comment by wolterhv** [comment]
Ok that's great!

**Comment by anufrievroman** [comment]
Updated.
