### ISSUE TITLE
Unable to sync Google Calendar

### ISSUE THREAD

**Issue by marcotroisi** [anufrievroman/calcure#111]
I'm experiencing the following errors:

```
$ cat .config/calcure/info.log 
[ERROR] Failed to load from https://calendar.google.com/calendar/ical/marco%40trilo.io/public/basic.ics. Probably url is wrong. HTTP Error 404: Not Found
[ERROR] Failed to parse https://calendar.google.com/calendar/ical/marco%40trilo.io/public/basic.ics. Found no components where exactly one is required: 
```

My config file looks like this:

```
[Parameters]
folder_with_datafiles = ~/.config/calcure
calcurse_todo_file = ~/.local/share/calcurse/todo
calcurse_events_file = ~/.local/share/calcurse/apts
language = en
default_view = calendar
default_calendar_view = monthly
birthdays_from_abook = Yes
show_keybindings = Yes
privacy_mode = No
show_weather = No
weather_city = 
weather_metric_units = Yes
minimal_today_indicator = Yes
minimal_days_indicator = Yes
minimal_weekend_indicator = Yes
show_calendar_borders = No
cut_titles_by_cell_length = No
ask_confirmations = Yes
ask_confirmation_to_quit = Yes
use_unicode_icons = Yes
show_current_time = No
show_holidays = Yes
show_nothing_planned = Yes
one_timer_at_a_time = No
holiday_country = UnitedStates
use_persian_calendar = No
start_week_day = 1
weekend_days = 6,7
refresh_interval = 1
data_reload_interval = 0
split_screen = Yes
right_pane_percentage = 25
journal_header = JOURNAL
event_icon = •
privacy_icon = •
today_icon = •
birthday_icon = ★
holiday_icon = ⛱
hidden_icon = ...
done_icon = ✔
todo_icon = •
important_icon = ‣
separator_icon = │
deadline_icon = ⚑
ics_event_files = https://calendar.google.com/calendar/ical/**my-email**/public/basic.ics

[Colors]
color_today = 2
color_events = 4
color_days = 7
color_day_names = 4
color_weekends = 1
color_weekend_names = 1
color_hints = 7
color_prompts = 7
color_confirmations = 1
color_birthdays = 1
color_holidays = 2
color_todo = 7
color_done = 6
color_title = 4
color_calendar_header = 4
color_important = 1
color_unimportant = 6
color_timer = 2
color_timer_paused = 7
color_time = 7
color_deadlines = 3
color_weather = 2
color_active_pane = 2
color_separator = 7
color_calendar_border = 7
color_ics_calendars = 2,3,1,7,4,5,2,3,1,7
color_background = -1

[Styles]
bold_today = No
bold_days = No
bold_day_names = No
bold_weekends = No
bold_weekend_names = No
bold_title = No
bold_active_pane = No
underlined_today = No
underlined_days = No
underlined_day_names = No
underlined_weekends = No
underlined_weekend_names = No
underlined_title = No
underlined_active_pane = No
strikethrough_done = No

[Event icons]
travel = ✈
plane = ✈
voyage = ✈
flight = ✈
airport = ✈
trip = 🏕
vacation = ⛱
holiday = ⛱
day-off = ⛱
hair = ✂
barber = ✂
beauty = ✂
nails = ✂
game = ♟
match = ♟
play = ♟
interview = 🎙️
conference = 🎙️
talk = 🎙️
dating = ♥
concert = ♪
dance = ♪
music = ♪
rehearsal = ♪
call = 🕻
zoom = 🕻
deadline = ⚑
over = ⚑
finish = ⚑
end = ⚑
doctor = ✚
dentist = ✚
medical = ✚
hospital = ✚
party = ☘
bar = ☘
museum = ⛬
meet = ⛬
sport = ⛷
gym = 🏋
training = ⛷
email = ✉
letter = ✉
```

Appreciate the help. Love calcure!

Thanks :pray:

**Comment by anufrievroman** [comment]
I think the ulr might be wrong, usually it has a slightly different format as:
```
https://calendar.google.com/calendar/ical/myemail%40gmail.com/private-xxx/basic.ics
```
For example, if you just enter your URL in your browser, does it download ics file?

**Comment by anufrievroman** [comment]
Any further help needed with this issue?

**Comment by marcotroisi** [comment]
Apologies for the late reply! 

I see what you mean but, in this case, since the URL is coming from a
Google Workspace account, that URL is all I can get my hands on. It's a
"public" URL.

Upon researching this, it seems that the admin of the Google Workspace
account needs to enable something on their side in order for "private"
ics URLs to be available.

I suspect I'm not alone in this. In fact, it's quite possible that most
Google Workspace accounts only have that URL available by default. 

Is there anything that could be done to ingest those URLs? I'd imagine
the content is not that dissimilar to the private URL that is normally
found in personal Gmail accounts.

Thanks!

On October 19, 2024, Mitchell Valine ***@***.***> wrote:
> Any further help needed with this issue?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/anufrievroman/calcure/issues/111#issuecomment-
2423428213>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AADI5QB7SLWYDWV5REO6QFDZ4GYITAVCNFSM6AAAAABPQGOZLKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRTGQZDQMRRGM>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by anufrievroman** [comment]
I mean a public URL is fine too, in principle any ics file should work, but anyway the URL from your logs above is not available, so calcure naturally can't download ics file from it. To be honest, I'm not familiar with workspaces, but the point is that the ics file should be downloadable without login to Google.

**Comment by anufrievroman** [comment]
Also, if public URL is not possible to setup for Google workspaces for some security reasons, you may look into tools (see documentation) to download (periodically) this file locally and then just pointing calcure to the local version of the file.

**Comment by anufrievroman** [comment]
I'll close this issue in a few days if no further assistance is neede.
