### ISSUE TITLE
CalDAV support

### ISSUE THREAD

**Issue by 3nprob** [anufrievroman/calcure#13]
Would be great if calcure supported [CalDAV](https://devguide.calconnect.org/CalDAV/introduction/) syncing for interoperability with other clients and servers.

**Comment by tombh** [comment]
If calcurse supports CalDAV, then can calcure support CalDAV indirectly?

**Comment by mathstuf** [comment]
#4 and `vdirsyncer` is another solution to supporting CalDAV.

**Comment by anufrievroman** [comment]
Yes, I'd say the ics files and syncing with `vdirsyncer` is the best solution, because writing my own syncing module is probably something unrealistic at the moment. But I'll check if there are some libraries avalible.

**Comment by anufrievroman** [comment]
I'll close this issue because the discussion moved to the issue #4

**Comment by 3nprob** [comment]
While there is discussion regarding CalDAV in comments in #4, the issue itself is only regarding ICS file support. Maybe the issue can be changed to indicate that it also concerns remote CalDAV if this is to be closed as duplicate?

**Comment by anufrievroman** [comment]
Oh, okay, you meant the issue like the protocol support from the application itself? Okay, let's keep it open for now, but indeed, I'd say the vdirsyncer seems the most adequate way to go because it will be difficult (for me) to support all the sync functionality. But if anyone has any ideas or alternatives to vdirsyncer, please.

**Comment by anufrievroman** [comment]
Hello, it's been a while. Basically, at this point we totally went the `vdirsyncer + ics` route, so I think native CalDAV sync will not be considered in the foreseeable future. So, I'll close this issue for now. Thank you for the discussion!
