### ISSUE TITLE
How can I add the Iran holiday to Calcure?

### ISSUE THREAD

**Issue by xmha97** [anufrievroman/calcure#15]
How can I add the Iran holiday to Calcure project?
```
holiday_country = Iran
```

**Comment by anufrievroman** [comment]
The holidays are loaded from python's 'holidays' library; the list of countries it supports is here:

https://python-holidays.readthedocs.io/en/latest/

Unfortunately, it looks like Iran is not there yet, thought they are expanding quickly. Perhaps you can open an issue there or contribute to that library.

**Comment by xmha97** [comment]
OK, thanks.

**Comment by anufrievroman** [comment]
By the way, in the new version, you can view .ics files. So you could download .ics of holydays in Iran, for example from google calendar, and read it in calcure by adding in config:
```
ics_event_files = /home/username/.config/vdirsyncer/data/my_iranian_holidays.ics
```
