### ISSUE TITLE
Color of the first line

### ISSUE THREAD

**Issue by xmha97** [anufrievroman/calcure#16]
Why does the color of the first line change? `KHORDAD 1401`

![WindowsTerminal_bCvZTRitlw](https://user-images.githubusercontent.com/23485114/172052451-ff5493c4-a540-4e92-bee4-7b4baaa7e935.gif)

**Comment by anufrievroman** [comment]
When in split screen mode, color indicates which side is currently active, you can switch between journal and  calendar with space. You can use other highlights instead, for example bold or underline if your terminal supports.

**Comment by xmha97** [comment]
OK, thanks.
