### ISSUE TITLE
3rd or alternate view in the future

### ISSUE THREAD

**Issue by gokaybalci** [anufrievroman/calcure#2]
Do you have anything in mind about a combined view of calendar and tasks that we can see both pages side to side?
They can both have similar keybinds except we can use SuperKey for the latter page etc.

It doesnt have to be default or a third page per se. Maybe we can change a config setting to get that page and make it default?

**Comment by anufrievroman** [comment]
Hello, yes, I've been thinking about it from day one, actually. I imagine it as a screen split in two and on pressing Tab we switch activity between right (journal) and left (calendar) views, so all keys are applied to the view that is currently active.
I even already implemented proper resizing of calendar for this purpose, but the way the code is currently written, it would require a huge copy/paste to implement this, so I'm still thinking that there should be some smart way to code it without huge duplication of the code... let's keep this issue open for now.

**Comment by anufrievroman** [comment]
It's been a while, but finally I rewrote the program almost from scratch and implemented split screen as a side effect, it is commit cf7945ac9ba0a2af2df208604404b44e2fd7e183 
This will be available in the upcoming version 2.0 once I polish out all new bugs.
