### ISSUE TITLE
Proper packaging for AUR

### ISSUE THREAD

**Issue by anufrievroman** [anufrievroman/calcure#20]
Does anyone know how to properly package python packages for AUR? Previously I just had a single file, so it was easy to package, but with many modules, I'm not sure how to package it now and the version of AUR package is stack at 1.8. Thank you.

**Comment by nogweii** [comment]
check out https://wiki.archlinux.org/title/Python_package_guidelines

and looking at your `setup.py`, you depend on the holidays & jdatetime libraries. there is an AUR package for holidays (https://aur.archlinux.org/packages/python-holidays) but not one for jdatetime. You'd need to package the dependency as it's own AUR package, too, to make it complete.

**Comment by anufrievroman** [comment]
Thank you, I see what to do, I guess. I guess now I'll have to maintain the AUR for jdatetime as well...
