### ISSUE TITLE
Rename calcure to calcure.py

### ISSUE THREAD

**Issue by xmha97** [anufrievroman/calcure#3]
Rename `calcure` to `calcure.py`

**Comment by anufrievroman** [comment]
Hi, the reason why it is made like this is that people can just drop this file into their bin folder and run on any linux distro, without seriously 'installing' it. Once I figure out better ways to distribute the software (maybe with pip or something) for many OSs and distros, I'll refactor this repo to have code properly split into modules etc.

**Comment by anufrievroman** [comment]
By the way, it is fixed like described. Now package can be installed from PyPi
