### ISSUE TITLE
Different timer can run at the same time

### ISSUE THREAD

**Issue by therealmaxmoon** [anufrievroman/calcure#30]
It is possible to start n amount of timers, which doesn't make sense in real life, because everyone can only work on one task at a time. 

**Solution:**

Stop running timer automatically if the user wants to start another timer.

**Comment by anufrievroman** [comment]
Well, I can counter-example it with one time for general "work" and different timers for subtasks running at the same time. But perhaps you are right that it could be an option to allow only one timer at a time. I'll look into it.

**Comment by therealmaxmoon** [comment]
I wouldn't recommend to have 2 timers at the same time for the main and sub task. This would falsify the data, if you use external tools to calculate how much time you invested in total in a single project. 

Maybe overkill, but showing the total time behind the main task, which was invested for all sub tasks, could help people who are doing time blocking. But like I said, it might be overkill and a slim software should stay slim and features like this should be something for external tools. 

Personally I even use other tools to track my time, trying to use tools, which are following the unix philosophy:

> Do one thing and do it well

**Comment by anufrievroman** [comment]
Hi, I just uploaded a version 2.5.3 in which you can set a setting `one_timer_at_a_time = yes`. Then it functions like you requested :)
