### ISSUE TITLE
event times & country holidays

### ISSUE THREAD

**Issue by k4y4k** [anufrievroman/calcure#32]
hello 👋 i really like this ♥ its much better than calcurse

however, i have 2 questions

1. does calcure deal with event times? e.g. i want "daily standup" at 0900, and stuff before that above it in the list. is this something ill have to bring in via ics or something?

2. i set `holiday_country = Australia` in my config, but im not seeing stuff like Australia Day (26 Jan) appear. i read the `python-holidays` docs linked in the wiki, but its not making much sense to me 😔 i live in the `QLD` subdivision, but im not sure how to select that via calcure's config?

thank you in advance for your time 🐨✌

**Comment by anufrievroman** [comment]
Hello, thank you!

1. At the moment calcure does not support isc, and the time is simply a part of the description, i.e. it's not a separate field. I started this project as a kind of simplified calendar without numerous fields, as personally I never used the time of events as a separate field. However, with ics integration I'll have to integrate it somehow, but for now, events have only date, description, and status.

2. Well, there actually wan an issue with holidays, my bad. I fixed it in version 2.5.6, now it works, please upgrade:
`python install calcure --upgrade`

p.s. by the way, at the moment calcure does not support subdivisions, let me know if this is critical and some holidays are missing if you just set `Australia`, I can implement subdivisions later.

**Comment by k4y4k** [comment]
wow! so quick!

1. fair enough. i wasnt sure what the overall status re: ics *was* so i thought i'd ask 😄.
2. it works! 🎉 thank you very much.

p.s. subdivisions arent critical in the slightest. in fact its such a non issue i was surprised to see it even supported. really don't worry about adding it (if it becomes important to me, i can e.g. sub to apple / google's holiday .ics)
