### ISSUE TITLE
the border isnt align properly

### ISSUE THREAD

**Issue by bryant-the-coder** [anufrievroman/calcure#34]
![image](https://user-images.githubusercontent.com/92417638/209814973-3a4cac37-3a04-430e-ae72-626c37105e04.png)
As you can see, beside date 25. the border isnt align properly. any fix to it?

Terminal: kitty
Font: Operator Mono SSm Lig Book Nerd Font
OS: Fedora

**Comment by anufrievroman** [comment]
I know this bug, usually, this is related to the fact that in your font some characters are not really monospace. In this case, I guess, the leaf icon is probably taken from backup font or something like that, so it takes up more space and shifts the whole line. Usually, Nerd fonts are good, but I am not familiar with this one. By chance, could you please check with another font?

In any case, it is not something I can fix in the program, but you can change this icon in the config file into something else, for example:
`holiday_icon = •`

**Comment by anufrievroman** [comment]
I installed Kitty to check, it occurs even with my font (Noto Sans Nerd). So it seems it has something to do with how Kitty interprets certain characters. Maybe I should change default holiday icon in the future

**Comment by bryant-the-coder** [comment]
> I know this bug, usually, this is related to the fact that in your font some characters are not really monospace. In this case, I guess, the leaf icon is probably taken from backup font or something like that, so it takes up more space and shifts the whole line. Usually, Nerd fonts are good, but I am not familiar with this one. By chance, could you please check with another font?
> 
> In any case, it is not something I can fix in the program, but you can change this icon in the config file into something else, for example: `holiday_icon = •`

![image](https://user-images.githubusercontent.com/92417638/209895504-ce23288c-1133-43fe-8578-60e03035b00a.png)
so this works 🤔

**Comment by anufrievroman** [comment]
So hopefully it's just this one icon. If in future you have font troubles, you can just set `use_unicode_icons = No` to only use ascii symbols, that will make sure that everything is fine.

**Comment by bryant-the-coder** [comment]
Thanks bud. Btw nice config :)

**Comment by anufrievroman** [comment]
Thank you :)

**Comment by anufrievroman** [comment]
The default holiday icon has been changed to ⛱ to fix this for all kitty users.

**Comment by bryant-the-coder** [comment]
> The default holiday icon has been changed to ⛱ to fix this for all kitty users.

Sorry the late reply. Thanks for the change! Been seeing lots of commits!! Lets go!
