### ISSUE TITLE
Local ics file doesnt show in calendar

### ISSUE THREAD

**Issue by ShaneWikerSWE** [anufrievroman/calcure#39]
I'm using IFTTT to sync my Google Calendar to Dropbox. Locally the file exists and has data, yet when I import it like this and restart calcure, none of the events show. What am I doing wrong? Is there someway to troubleshoot it by looking at logs?

[Parameters]
ics_event_files = "/home/ShaneWikerSWE/Dropbox/IFTTT/Google Calendar/shanewikerswe_calendar.ics"
folder_with_datafiles = /home/ShaneWikerSWE/.config/calcure
calcurse_todo_file = /home/ShaneWikerSWE/.local/share/calcurse/todo
...

**Comment by anufrievroman** [comment]
Hi, I think you need to remove quotation marks from the path

**Comment by ShaneWikerSWE** [comment]
Ahh you were right, I thought it was ok since the documentation said to use quotes if using more than one file. Thank you!
