### ISSUE TITLE
Multiple calendars in one ics file

### ISSUE THREAD

**Issue by eguiraud** [anufrievroman/calcure#41]
Hi,

I tried out calcure after the reddit post the other day. It looks great, fits my setup perfectly (nextcloud for calendar, taskwarrior for tasks!).

However setting up the calendar sync I receive the titular error:

```
NotImplementedError: Multiple calendars in one file are not supported by this method. Use ics.Calendar.parse_multiple()
```

where my `calcure/config.ini` is the default plus these two lines right after `[Parameters]`:

```
ics_event_files = /home/blue/.config/vdirsyncer/data/events.ics
folder_with_datafiles = /home/blue/.config/calcure
```

and my vdirsyncer config is 

```
[general]
status_path = "~/.vdirsyncer/status/"

# Sync events

[pair events]
a = "events_local"
b = "events_remote"
collections = null

[storage events_local]
type = "singlefile"
path = "~/.config/vdirsyncer/data/events.ics"

[storage events_remote]
type = "caldav"
url = "XXX/nextcloud/remote.php/dav"
username = "XXX"
password.fetch = ["shell", "XXX"]
```

Before I try to patch this for my case (the error message suggests that switching to `ics.Calendar.parse_multiple()` might do the job) I thought I'd ask whether there is already a way to support multiple calendars in calcure.

**Comment by anufrievroman** [comment]
Hi, thank you for reporting!
I didn't know you can put several calendars into one file. So you have more than one calendar in your nextcloud, right?
The way it meant to be used is that different calendars are in different ics files (probably need to change the vdirsyncer settings (collections?) and then in calcure config they are listed as:
```
ics_event_files = /home/blue/.config/vdirsyncer/data/events1.ics,/home/blue/.config/vdirsyncer/data/events2.ics
```
(no quotes, no spaces).

However, if this is not working for you, we may look into this `ics.Calendar.parse_multiple()`. I'll try to replicate your error and see...

**Comment by eguiraud** [comment]
Thank you for the quick reply!

Yes I have a "personal" and a "work" calendar on Nextcloud and it looks like vdirsyncer puts them in the same ics file.

I'll try to figure out how to tell vdirsyncer to use one file per calendar when I have some spare time.

**Comment by anufrievroman** [comment]
Actually, I found a quick fix for you. In you vdirsyncer config, you can specify which calendar to sync as:
```
url = "https://XXX/remote.php/dav/calendars/admin/personal"
```
So you need to create two sync records, one for work, another for personal. The whole config would look something like:

```
[general]
status_path = "~/.vdirsyncer/status/"

# Sync events personal

[pair events_personal]
a = "events_local_personal"
b = "events_remote_personal"
collections = null

[storage events_local_personal]
type = "singlefile"
# type = "filesystem"
path = "~/.config/vdirsyncer/data/events_personal.ics"
# fileext = "ics"

[storage events_remote_personal]
type = "caldav"
url = "https://.../remote.php/dav/calendars/admin/personal"
username = "..."
password = "..."

# Sync events work

[pair events_work]
a = "events_local_work"
b = "events_remote_work"
collections = null

[storage events_local_work]
type = "singlefile"
# type = "filesystem"
path = "~/.config/vdirsyncer/data/events_work.ics"
# fileext = "ics"

[storage events_remote_work]
type = "caldav"
url = "https://.../remote.php/dav/calendars/admin/work"
username = "..."
password = "..."
```

But let's keep this issue open. It definitely should not crash like that, so I'll see how to improve it.

**Comment by anufrievroman** [comment]
Well, so for me, the `ics.Calendar.parse_multiple()` didn't really work, it just seem to return empty list. So for now I just fixed crash, but people will have to separate calendars I guess.

**Comment by eguiraud** [comment]
Thank you for the fix/workaround! Given that it's even in the wiki now, that counts as a solution for me :+1:

**Comment by anufrievroman** [comment]
Okay, I'll close it then, since I don't really see what else I can do here. Thank you for reporting.
