### ISSUE TITLE
Display of errors

### ISSUE THREAD

**Issue by anufrievroman** [anufrievroman/calcure#44]
Need to implement a system to propagate errors and display to the user.
For instance, if some of the files were not loaded, there should be a message to the user or at the very least a log file.

**Comment by nfultz** [comment]
I noticed this when in the codebase yesterday playing with ICS config.

- first step is to replace  print()s at https://github.com/anufrievroman/calcure/blob/fe6203a1c5a7a5130f51b0170e7dee5ef1476696/calcure/configuration.py#L297-L302
- Also would be nice to (optionally) log exception and stack trace.

 See also https://docs.python.org/3/howto/logging.html

**Comment by anufrievroman** [comment]
Implemented 020aa700141ab4e2d9a17396a73adda20ed11c05 basic logging of errors and warning into log file and console.
In the future, should also display the errors in curses interface, at least after the start of the app, or maybe just a message like "Errors occurred, see info.log file".

**Comment by anufrievroman** [comment]
Commit 868c3ead0442333aae35642b3c547117cd7275a8 adds display of error notification in curses interface.
So the issue is resolved. Maybe later the errors could be summarized more explicitly. Maybe I'll also introduce the same notification for incorrect input from the user.
