### ISSUE TITLE
Priorities and nested subtasks

### ISSUE THREAD

**Issue by ura43** [anufrievroman/calcure#5]
Hi, first of all cool project. Thought of writing a calcurse clone myself, but yours seems pretty good already, at least from a ui standpoint.

For tasks, wouldn't it make sense to at least have a priority integer that goes from like 0-9 by default, or a mask that says sth like low medium high?
Also, I can't seem to create subtasks for a subtask.
Maybe tags are a good idea?

How many features are necessary for keeping a good todo list are highly subjective, but maybe listing the features you would consider useful in a seperate segment of the readme could help clarify things.
Your tool is too simple for me, while taskwarrior is overly complex.
I may just write my own task management tool anyway, but please write up your desired scope / workflow.

**Comment by anufrievroman** [comment]
Hi, thank you for the feedback!

From a philosophical point of view, one of my goals with this app was to achieve simpler and faster operation than in calcure. That is why some functions, like priority, are reduced to just two states: normal/important. But indeed, I think I could add one more state, like low priority, so it would be a choice between low/normal/high priority, which should cover most needs.

Similarly, about the subtasks, I thought it would be better to sacrifice sub-sub-tasks for the sake of simple toggling task/sub-task state. Personally, I never even use subtasks, but I imagine some people might need it. So, how many levels of nested subtasks would you realistically use?

**Comment by ura43** [comment]
Personally, I rarely even use sub-sub tasks myself, but I think they are about as deep as is practical and I have used them a few times in the past.
For priorities, I really like the "unset/low/normal/high" paradigm used by [tasks](https://github.com/tasks/tasks), the android app I used for task management for several months. 
For simplicity, low / normal / high is enough with normal being a default priority

**Comment by anufrievroman** [comment]
Just added these two features in the last commit. Will appear in the next release
- Third level of subtasks. Now subtask added to a subtask will create a subsubtask. However, toggling with `s` will toggle only first level - kind of a reasonable compromise.
- Low priority tasks with `l`. So now it can be normal/important/unimportant/done.

**Comment by ura43** [comment]
> Just added these two features in the last commit (already in repositories).
> 
> * Third level of subtasks. Now subtask added to a subtask will create a subsubtask. However, toggling with `s` will toggle only first level - kind of a reasonable compromise.
> * Low priority tasks with `l`. So now it can be normal/important/unimportant/done.

Greatly appreciate it, I consider this issue resolved :)
