### ISSUE TITLE
Weather units can't be set

### ISSUE THREAD

**Issue by Scary-Guy** [anufrievroman/calcure#59]
I just want a simple weather_units = C / F.  I didn't see anything in the documentation or example .ini regarding this.

**Comment by anufrievroman** [comment]
Hi, added this feature on your request. Please update to version 2.9.1 and the following to your config

```
weather_metric_units = No
```

**Comment by Scary-Guy** [comment]
I think you meant Yes, but in any case thank you for pushing an update just for this!  I'd have been happy waiting until the next one but this is awesome.  Keep up the great work.
