### ISSUE TITLE
Ability to mark single instance of a recurring event as done

### ISSUE THREAD

**Issue by andrewpdawes** [anufrievroman/calcure#60]
Hi

It would be helpful to be able to mark each individual instance of a recurring event as 'done'. Currently, when one instance is marked as 'done', all instances become marked as 'done'.

Thanks for the great work.

Cheers

Andy

**Comment by anufrievroman** [comment]
Hi, thank you for the suggestion. It is a very reasonable idea, from user's perspective, but I have no idea how to implement it :D You see, the recurring events are stored as a single entry in the database, just with the additional property of repetition N times. As such, any status applied to the entire record. Actually, the recurring events are a huge headache. But if you or anyone has any ideas, please share.

**Comment by andrewpdawes** [comment]
Hi. 

I appreciate your honesty :-) and thanks for the explanation.

Unfortunately, I do not have the technical ability to make the changes. Let's hope that someone who reads this is able to contribute.

Thanks again for the quick reply.

Cheers

Andy
