### ISSUE TITLE
Language of holiday events

### ISSUE THREAD

**Issue by xmha97** [anufrievroman/calcure#62]
I set `holiday_country = Iran` on Ubuntu and Windows.
On Ubuntu, I see holiday events in English.
![image](https://github.com/anufrievroman/calcure/assets/23485114/76a091b0-c13e-4344-a465-dba3d8c8f0de)
But on Windows, I see holiday events in Persian.
![image](https://github.com/anufrievroman/calcure/assets/23485114/03338aa8-2c12-42bf-9a40-1e69d888974a)
Why?

**Comment by anufrievroman** [comment]
This is controlled by `holidays` library and I think is related to the version used and how it extracts locale from the system. I noticed the change of the language as well. I think it's better to ask this at that library. Here, I have no control over it.

**Comment by anufrievroman** [comment]
Specifically, Iran is [supported in two languages](https://python-holidays.readthedocs.io/en/latest/), so `holidays` python lib chooses the language depending on your system, not sure how. Check their documentation via that link to possibly fix that. I think you'll need to add `fa` locale to display it in Persian, but I can't be sure.

**Comment by jose1711** [comment]
Interesting, on my Arch system I see the holidays names are shown in Persian. I also get them in Python:
```
python -c 'from holidays import countries; print(list(countries.Iran(2023).values())[:3])'
['نوروز', 'نوروز', 'نوروز']
```
`python-holidays` = 0.34.

**Comment by anufrievroman** [comment]
I think there's a default language for each country in `holidays` library and some additionally supported languages. So, if your LANG is anything but en_US then by default it's in Arabic, but if it's specifically en_US then `holidays` displays events in the additionally supported English language. 

Again, this is not something I can override, so I'll close this issue.
