### ISSUE TITLE
Support time for events

### ISSUE THREAD

**Issue by jose1711** [anufrievroman/calcure#65]
Calcure treats all events as all-day. Importing calendars from `.ics` where multiple events are present on the same day with different time it looks as follows:
![obrázok](https://github.com/anufrievroman/calcure/assets/1406222/51ca684b-e4ed-426e-a985-d665cc66f4ca)
Time information is there but since Calcure does not understand it, there is no sorting and it's quite hard to navigate.

**Comment by anufrievroman** [comment]
Thank you for the suggestion. Indeed, now the time is just displayed as text and not really considered. I see now how it can become a problem. To be honest, I am not sure if calcure is the best tool for heavy time management :D But I'll see how it can be improved.

**Comment by anufrievroman** [comment]
![2023-11-22_11-33](https://github.com/anufrievroman/calcure/assets/42904990/799ebc8a-a1e4-4666-811a-7d088ebda07c)
Fixed that in commit 5e652d3b6b26c1056c9ce9749da45cce78a1cb1a 
Looks okay to me, but I tested only on few events, please check.
