### ISSUE TITLE
Support Persian Calendar

### ISSUE THREAD

**Issue by xmha97** [anufrievroman/calcure#7]
Please support [Persian Calendar](https://en.wikipedia.org/wiki/Solar_Hijri_calendar) (like jcal on Linux)

![image](https://user-images.githubusercontent.com/23485114/151901569-6fb79763-6abd-440c-b9b3-d74efe1e64f7.png)
https://github.com/ashkang/jcal

**Comment by anufrievroman** [comment]
Hmm, interesting. To just start week on Saturday you already can set start_week_day = 6 in setting, but to have the different number of days in the months, I'll need to check some alternative python calendar modules. I'll look into it, it seems not very difficult to support.

**Comment by xmha97** [comment]
# Persian Year
Persian Year≃Gregorian Year-621

# The number of days per Persian month:
1. Farvardin (31 days)
2. Ordibehesht (31 days)
3. Khordad (31 days)
4. Tir (31 days)
5. Mordad (31 days)
6. Shahrivar (31 days)
7. Mehr (30 days)
8. Aban (30 days)
9. Azar (30 days)
10. Dey (30 days)
11. Bahman (30 days)
12. Esfand (30 days)

# Days of the Week
| No | English   | Persian       |
|----|-----------|---------------|
| 1  | Saturday | Shanbeh       |
| 2  | Sunday   | Yekshanbeh    |
| 3  | Monday    | Doshanbeh     |
| 4  | Tuesday   | Seshanbeh     |
| 5  | Wednesday | Chaharshanbeh |
| 6  | Thursday  | Panjshanbeh*  |
| 7  | Friday    | Jomeh*        |

**Comment by xmha97** [comment]
How I can change weekends days?
On the Persian calendar, weekends are Thursday and Friday.

**Comment by anufrievroman** [comment]
At the moment you can change the weekend days, I'll add it.

Notes to myself: 
- I'll need to use `jdatetime` and `jcalendar` libraries for Jalali implementation of Python’s datetime and calendar modules.
- Add a parameter to choose which days are weekend.

**Comment by xmha97** [comment]
Having a Persian calendar in the terminal for me is a dream. Thank you for your support.

**Comment by anufrievroman** [comment]
Okay, I've been away for while, there was an important job interview :)
Now I'm back to this project. I already implemented the possibility to choose any ways as weekends. 

In the upcoming version 1.8 (not published yet) there will be a new parameter:
`weekend_days = 6,7`, where 6 and 7 are the weekend days (i.e. Saturday and Sunday). This just changes highlighting, basically.
You also have the parameter: 
`start_week_day = 1` which says on which day we start the week (Monday by default).
Now, I need to add the Persian system.

**Comment by anufrievroman** [comment]
Well, in the end I had to reimplement both core and jcalendar libraries, but finally I did it, the Persian calendar works!
Commit 7c7e21fe64682a2b6f064d1c9a9e8cc44e5c063e implements this feature. This will be available in the upcoming version 2.0. I'll try to fix all small bugs and ship it to repositories in May. 

If you'd like to try an early preview, please install `jdatetime` library and use this branch: https://github.com/anufrievroman/calcure/tree/oop-rewrite

How it works:
You can use Persian calendar either running the program with the key `-j` like `calcure.py -j` or permanently set it in the config file `use_persian_calendar = Yes`.
All your events are stored in the Gregorian format and only displayed in the Persian format, so all your previous events should be displayed correctly.

**Comment by xmha97** [comment]
Thanks, it works fine. 🌹
![image](https://user-images.githubusercontent.com/23485114/172003641-0aebd274-c6fa-47dd-8e50-a4067ea62064.png)
