### ISSUE TITLE
Expand tilde in path names

### ISSUE THREAD

**Issue by jose1711** [anufrievroman/calcure#70]
It is a common practice to expand tilde in paths. `Calcure` does not do that and a user need to specify full path to a file/directory each time.
```
# this works
ics_event_files = /home/user/.calendars/gmail.ics

# this does not
ics_event_files = ~/.calendars/gmail.ics
```

**Comment by anufrievroman** [comment]
I think I fixed it in  e88d9a53d0094e639128e244500299062e4eeb24 but it requires some testing, please check if it works for you.

**Comment by anufrievroman** [comment]
By default, I'd prefer a full system path because the ~ expansion only works in unix via $HOME variable. Not sure what would happen in Windows and what's considered home there.

**Comment by jose1711** [comment]
The expansion also works on Windows:
```
import os
os.path.expanduser(`~')
# 'C:\\Users\\username'
os.path.expanduser(`~otheruser')
# 'C:\\Users\\otheruser'
```

**Comment by anufrievroman** [comment]
Okay, with  78913c4d4ecd55e76232fab223114e94a18ea000 it is shortened by default. Although I didn't test on Windows yet.
