### ISSUE TITLE
Calcure always wants to read .abook/addressbook

### ISSUE THREAD

**Issue by jose1711** [anufrievroman/calcure#71]
The config option `birthdays_from_abook` only controls whether birthdays are displayed in the calendar. Regardless the value of setting the `addressbook` file is always attempted to read.

This also means if the file does not exist each time `calcure` is executed a warning is generated in the log file:
```
[WARNING] Couldn't load birthdays. File. /home/user/.abook/addressbook does not exist.
```
In addition to that `calcure` shows somewhat meaningless `Incorrect input.` text in the status line.

**Comment by anufrievroman** [comment]
I see, yes, it's weird.
Fixed it in commit e8233e2f4b9cc305609e408e97100969ac65e452 Now if you turn it off in the config, no error occurs.
The error feedback to the user is still under construction, which causes the generic `Incorrect input` line, but this is a separate problem.
