### ISSUE TITLE
Tasks imported from TaskWarrior contain backslash

### ISSUE THREAD

**Issue by jose1711** [anufrievroman/calcure#76]
* add task via `taskwarrior`
`task add 'delete /foo/bar'`
* press <kbd>W</kdb> in `calcure`
* task is displayed as `delete \/foo\/bar`

It's probably safer to use taskwarrior bindings for Python.
```
import taskw
taskw = taskw.TaskWarrior()
tasks = filter_tasks({'status': 'pending'})
[x['description'] for x in a.filter_tasks({'status': 'pending'})][-1]  # 'delete /foo/bar'
```

**Comment by anufrievroman** [comment]
Fixed this with  4fbd301d456efb591957b085a3dc9d4934e59757 where I implemented import via taskw library. It's actually a pretty cool library, I think in future we may consider full sync with taskwarrior.
