### ISSUE TITLE
Question regarding events and tasks.

### ISSUE THREAD

**Issue by PhosCity** [anufrievroman/calcure#9]
I just found calcure and I'm still trying to figure out if it's right for me or not. But in calcure it seems we have two distinct page between events and tasks so I wanted to ask what constitutes as task and what as event.

What I was trying to do was create a task and assign it to a particular date to remind me that I have to perform that task in that particular day but I couldn't figure it out. Is it possible in calcure?

**Comment by anufrievroman** [comment]
Hello, I am afraid at the moment tasks and events are completely independent. I meant tasks more are a small todo list in addition to the main functionality of calendar. It is not too difficult to implement a functionality of making some kind of special events that also appear as tasks, but it is first time somebody requests this feature. I'll think about it.
Moreover, there is no reminder system at the moment, I am still not clear what would be the best way to implement it or if it is even needed in a TUI app.

**Comment by PhosCity** [comment]
Thanks for the response.

I think your idea of a special event is exactly what I'm looking for. For simplicity, a keybind to add the special event in Calendar page and in Task page to a particular day of the month, a way to change existing event or task to special event is what I'm looking for. That special event should probably be treated the same way as task that can be marked as done or important. An option to remove completed task from calendar view would be good too.

Also I think you misunderstood. I am not expecting calcure to remind me. I only want to look at the calendar view and look at the tasks I have to do today or tasks I have to complete until a particular day etc. So in essence, all calcure has to do is list the tasks in particular day of the month just like it currently lists the events.

**Comment by anufrievroman** [comment]
Hi, sorry for the delay, I've done with a big rewrite of the program, so now I'm about to start working on this issue. My idea is to implement it as "deadlines for tasks". For each task you can set a deadline day, which will be indicated in the calendar. 

p.s. to just view events of a particular day, you can also use the daily view, on calendar page `g` and chose the day. Plus now you can have a split screen with daily events on one side and tasks on the other side. So with task deadlines synced into calendar it should be almost what you described.

**Comment by anufrievroman** [comment]
I'll close this issue then.  Feel free to comment if there are any issues with this implementation or if you have more ideas.

**Comment by PhosCity** [comment]
Awesome. Thank you for implementing this feature!! I'll let you know if I have anything to say.
