### ISSUE TITLE
Update AUR package

### ISSUE THREAD

**Issue by anufrievroman** [anufrievroman/calcure#91]
It seems that the [AUR package](https://aur.archlinux.org/packages/calcure) became abandoned again. Perhaps someone knows how to contact the maintainer? 

Maybe we should just make a git package there? If someone could create a git package, that would be a great help.

**Comment by anufrievroman** [comment]
@Junker are you the maintainer? Please note that some dependencies changed, now we need: _holidays_, `jdatetime`, `icalendar`, and `taskw` python libraries.

**Comment by Junker** [comment]
updated.

**Comment by anufrievroman** [comment]
Thank you!
