### ISSUE TITLE
Support recurring events from .ics

### ISSUE THREAD

**Issue by anufrievroman** [anufrievroman/calcure#94]
Need to try implementing recurring events (not to be confused with multiday events) that are read from .ics files.

**Comment by dvragulin** [comment]
I'm waiting for this feature as a New Year's gift  :pray: :sweat_smile:

**Comment by anufrievroman** [comment]
I hope you mean 2025 :D 
At the moment, I am a bit occupied with other projects, so if someone want to take a look at this feature, please. I think step one is to check how `icalendar` library reads recurring events and try to read it, whatever information is there (frequency, number of repetitions etc). Once this is reliably read from .ics file, I'll help to add into proper object inside `caclure`.

**Comment by anufrievroman** [comment]
Hi @dvragulin , thanks to recent commit by @janusfil the recurring event have been implemented. It's currently in the main branch (not updated in the repositories yet). If you like to try please delete your installed version and install as:
```
pipx install git+https://github.com/anufrievroman/calcure
```

**Comment by janusfil** [comment]
> Hi @dvragulin , thanks to recent commit by @janusfil the recurring event have been implemented. It's currently in the main branch (not updated in the repositories yet). If you like to try please delete your installed version and install as:
> 
> ```
> pipx install git+https://github.com/anufrievroman/calcure
> ```

Or you can pass `--force` argument if you don't want to bother with deleting your current installation :slightly_smiling_face:
