### ISSUE TITLE
taskwarrior data not appearing

### ISSUE THREAD

**Issue by adriangalilea** [anufrievroman/calcure#98]
I just installed fresh taskwarrior 3.0 and calcure

When I add tasks to taskwarrior, calcure doesn't show them.

When I open calcure I see a message "incorrect input" not sure if related

I added
```
taskwarrior_folder = ~/.task
```

to my config.ini

And don't see any errors on the log, besides:
```
[WARNING] Couldn't load birthdays. File. /Users/adrian/.abook/addressbook does not exist.
```

Am I missing something?

**Comment by anufrievroman** [comment]
Thank you for reporting! 

I think it has something to do with their recent upgrade to 3.0 and migration of the data files [as described here](https://github.com/GothenburgBitFactory/taskwarrior/releases/tag/v3.0.0). `Calcure` relies on `taskw` python library to interact with `taskwarrior`, and I can see that this library is not really updated. So, I am not sure I am ready to support the migration from this new version of `taskwarrior` as it will probably require for me to write a parser for their new database (I don't know how difficult it is yet). Originally, this import from `taskwarrior` was meant to be just a migration tool for those who wants to try `calcure`, but now I am not sure how many people still cannot decide which one to use :D

Anyway, let's keep this issue open for now, I'll take another look on occasion, or maybe someone will be willing to implement import from the new database.

**Comment by anufrievroman** [comment]
So, at this point we will drop support for the Taskwarrior import since the library for that is abandoned and no longer works. I feel like spending time to develop my own parser is not worth it for such a niche feature, which was at early stages of the project, but perhaps now not that much. Sorry if this change affects your workflow.
